// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var MyError = /* @__PURE__ */Caml_exceptions.create("Demo.MyError");

$$Promise.$$catch(Promise.reject({
          RE_EXN_ID: MyError,
          _1: "test"
        }), (function (param) {
        return Promise.resolve("ok");
      }));

export {
  MyError ,
  
}
/*  Not a pure module */
